### ISSUE TITLE
force using third party implementation

### ISSUE THREAD

**Issue by naholyr** [tracker1/i-promise#1]
When using Promise in Node, Bluebird still has better perf and nice unhandledReject support that native does not have.

Finding a way in i-promise to return a specific implementation instead of systematically global.Promise would allow to use it in promisify-patch or even in specific subparts (modules) without overriding the whole Promise global.

I would see a non-breaking way of doing it via a submodule :

``` js
require("i-promise/config").use(require("bluebird”))
```

**Comment by naholyr** [comment]
See PR #2

**Comment by tracker1** [comment]
Thanks for the PR...  Would you please bump the node minor version... from there, I'll test and publish.

**Comment by naholyr** [comment]
Done :+1:
